export const userActions = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    GET_REQUEST: 'GET_TASKS_REQUEST',
    GET_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_FAILURE: 'GET_TASKS_FAILURE',

    ADD_REQUEST: 'ADD_TASK_REQUEST',
    ADD_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_FAILURE: 'ADD_TASK_FAILURE',
 
    LOGOUT: 'USERS_LOGOUT',

    SELECT_TASK: 'EDIT_SELECTED_TASK'
};
